// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetUUID() string
}

type Cluster struct {
	UUID        string      `json:"uuid"`
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	MasterNodes []*Instance `json:"masterNodes"`
	WorkerNodes []*Instance `json:"workerNodes,omitempty"`
}

func (Cluster) IsNode()              {}
func (this Cluster) GetUUID() string { return this.UUID }

type Instance struct {
	UUID             string   `json:"uuid"`
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	Description      *string  `json:"description,omitempty"`
	ProjectID        string   `json:"projectID"`
	Status           *string  `json:"status,omitempty"`
	AvailabilityZone []*Zone  `json:"availabilityZone"`
	Created          string   `json:"created"`
	Cluster          *Cluster `json:"cluster,omitempty"`
	MountedVolume    *Volume  `json:"mountedVolume,omitempty"`
}

func (Instance) IsNode()              {}
func (this Instance) GetUUID() string { return this.UUID }

type Pod struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	WorkerNode *Instance `json:"workerNode"`
	Schema     *string   `json:"schema,omitempty"`
	HasPii     bool      `json:"has_pii"`
	Volumes    []*Volume `json:"volumes,omitempty"`
}

type Schema struct {
	ID          string `json:"id"`
	Pod         *Pod   `json:"pod"`
	PrivacyInfo string `json:"privacyInfo"`
}

type Volume struct {
	UUID             string    `json:"uuid"`
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	Pod              *Pod      `json:"pod,omitempty"`
	AttachedInstance *Instance `json:"attachedInstance"`
}

func (Volume) IsNode()              {}
func (this Volume) GetUUID() string { return this.UUID }

type Zone struct {
	UUID             string `json:"uuid"`
	AvailabilityZone string `json:"availabilityZone"`
}

func (Zone) IsNode()              {}
func (this Zone) GetUUID() string { return this.UUID }
